### ISSUE TITLE
Document the build process

### ISSUE THREAD

**Issue by asomov** [clj-commons/clj-yaml#130]
I would like to make a change in the library and observe the result.
I expect some simple steps without major installation. Preferable without any installation at all since this is a library.

Context: I would like to evaluate the migration to SnakeYAML Engine

Is it possible to specify the steps to build the project in the developer's guide ?

**Comment by borkdude** [comment]
Hi @asomov ! It would be great if we could upgrade to SnakeYAML engine. However, Clojure libraries have a strong guarantee that they are backward compatible so hopefully it's possible to move to SnakeYAML engine without making (major) breaking changes to this library. 

You can do that as follows. Install the clojure CLI: https://clojure.org/reference/clojure_cli
Then you need to compile the Java sources in this library, per:
https://clojure.org/guides/deps_and_cli#prep_libs
This means you have to run: `clj -X:deps prep`

After that you can make a change to the Clojure code and run it, e.g. make a test script in the root directory:
`scratch.clj` and then run it with `clj -M scratch.clj`
Or you can run the test suite with: `clj -M:test`

The most optimal workflow for working with Clojure it to use a REPL, but the above hopefully gets you started quickly.

Let me know if you have any further questions.




Then change some code in the library.

**Comment by lread** [comment]
Hi @asomov, thanks for all your endless hard work on SnakeYAML!

I'm not sure if you are very familiar with Clojure yet. It is typically compiled at runtime, so no javac-like step is required.

If you want to follow the [dev guide](https://github.com/clj-commons/clj-yaml/blob/master/doc/02-developer-guide.adoc) as is, you'll need to install [babashka](https://github.com/babashka/babashka?tab=readme-ov-file#quickstart). 
You can then run our [project task](https://github.com/clj-commons/clj-yaml/blob/master/doc/02-developer-guide.adoc#babashka-taskss), like `bb test`.

To repeat @borkdude, if you get serious about Clojure development, using the [REPL](https://clojure.org/guides/repl/introduction) is the way to go.

All that said, I see that we did [kind of explore](https://github.com/clj-commons/clj-yaml/discussions/52) migrating from [SnakeYAML](https://bitbucket.org/snakeyaml/snakeyaml/src/master/) to [SnakeYAML Engine](https://bitbucket.org/snakeyaml/snakeyaml-engine/src/master/).
Like @borkdude mentioned, backwards compatibility is very important in the Clojure world. If something behaves differently or has a different API, we typically create a new library instead of a new version of an existing library.

If you are still interested in exploring, we are happy to try and help.
I'm not sure if you are interested in diving into Clojure, but if that's the case, we do have an active, friendly, and helpful community on [Slack](http://clojurians.net/).

**Comment by borkdude** [comment]
>  It is typically compiled at runtime, so no javac-like step is required.

This project is an exception, hence you need to run the prep-libs step so that the Java sources are compiled.

**Comment by lread** [comment]
Oh, right. Thanks, @borkdude. I forgot we have a couple of `.java` source files in this project!

**Comment by asomov** [comment]
I installed and run clojure -X:deps prep
Now I got an error when running tests:

$ clojure -M:test
Cloning: https://github.com/cognitect-labs/test-runner.git
Checking out: https://github.com/cognitect-labs/test-runner.git at dfb30dd6605cb6c0efc275e1df1736f6e90d4d73
Downloading: org/clojure/tools.cli/1.0.206/tools.cli-1.0.206.pom from central
Downloading: org/clojure/tools.namespace/1.3.0/tools.namespace-1.3.0.pom from central
Downloading: org/clojure/pom.contrib/1.0.0/pom.contrib-1.0.0.pom from central
Downloading: org/clojure/java.classpath/1.0.0/java.classpath-1.0.0.pom from central
Downloading: org/clojure/pom.contrib/0.2.2/pom.contrib-0.2.2.pom from central
Downloading: org/clojure/tools.namespace/1.3.0/tools.namespace-1.3.0.jar from central
Downloading: org/clojure/java.classpath/1.0.0/java.classpath-1.0.0.jar from central
Downloading: org/clojure/tools.cli/1.0.206/tools.cli-1.0.206.jar from central

Running tests in #{"test"}
Execution error (ClassNotFoundException) at java.net.URLClassLoader/findClass (URLClassLoader.java:476).
clj_yaml.MarkedConstructor

Full report at:
/tmp/clojure-3777967543594621203.edn

**Comment by lread** [comment]
@asomov I see that borkdude gave you some `clojure` commands, but it would be easier for me to support you if you followed the [developer guide](https://github.com/clj-commons/clj-yaml/blob/master/doc/02-developer-guide.adoc) and used `bb` tasks. You can think of this as our `make` command.

All you should have to run is `bb test` to run tests.

**Comment by asomov** [comment]
@lread I studied the developer guide. It does not mention any installation for bb.

**Comment by lread** [comment]
Thanks for the feedback @asomov, the developer guide assumes some familiarity with the Clojure ecosystem. I will add links to the [prerequisites](https://github.com/clj-commons/clj-yaml/blob/master/doc/02-developer-guide.adoc#developer-prerequisites) section to make it more friendly to newcomers. 

In the meantime, here's the quickstart link for [babashka](https://github.com/babashka/babashka?tab=readme-ov-file#quickstart).

**Comment by lread** [comment]
@asomov I added some links to [prerequisites](https://github.com/clj-commons/clj-yaml/blob/master/doc/02-developer-guide.adoc#developer-prerequisites), hopefully that helps you.

**Comment by asomov** [comment]
@lread thank you. I managed to install and run bb.
Unfortunately, I am unable to make the changes to migrate to the Engine.
But the library does not depend on magic Javabean creation and the migration to engine should not be complex.
If anyone decides to migrate - feel free to contact me for the assistance.

**Comment by lread** [comment]
Well, it is always nice to see you around @asomov! And thanks for the offer of help.

I am curious as to why you were interested in exploring this: Do you feel you want to deprecate SnakeYAML and move to only supporting SnakeYAML Engine? I can imagine supporting both is not an easy task!

**Comment by asomov** [comment]
@asomov yes, I would like to gradually migrate to the Engine.
But there is a big chunk of functionality which not yet in Engine. This has to be written/developed (as a separate library).
This chuck causes a lot of issues. But you do not use it.
