### ISSUE TITLE
Cannot generate yaml with indented list values

### ISSUE THREAD

**Issue by agorgl** [clj-commons/clj-yaml#136]
When doing yaml generation with the default options and block flow-style, list values of maps are not indented.

For example with this simple snippet:
```
(let [opts {:flow-style :block}]
  (yaml/generate-string data :dumper-options opts)
```

We get back this:
```
apiVersion: v1
kind: Pod
metadata:
  name: example
  labels:
    app: example
spec:
  containers:
  - name: example
    image: example:latest
```

But given that the common yaml practice is to indent values of maps that are lists, it is expected to be:
```
kind: Pod
metadata:
  name: example
  labels:
    app: example
spec:
  containers:
    - name: example
      image: example:latest
```

Setting both `:indent` and `:indicator-indent` to the same value (2) we get back:
```
Execution error (YAMLException) at org.yaml.snakeyaml.Yaml/<init> (Yaml.java:208).
Indicator indent must be smaller then indent.
```

In order to allow the above, clj-yaml must call the [DumperOptions/setIndentWithIndicator](https://www.javadoc.io/doc/org.yaml/snakeyaml/latest/org/yaml/snakeyaml/DumperOptions.html#setIndentWithIndicator(boolean)) with the param to true, that allows the above behavior.

For now I'm using the following hack to get around this problem:
```
(defn to-yaml [data]
  (let [yaml-opts {:indent 2
                   :indicator-indent 2
                   :flow-style :block}]
    (with-redefs [clj-yaml.core/default-dumper-options
                  (fn []
                    (doto (DumperOptions.)
                      (.setSplitLines false)
                      (.setIndentWithIndicator true)))]
      (yaml/generate-string data :dumper-options yaml-opts))))
```

Possible solutions would be to either add `(.setIndentWithIndicator true)` to default-dumper-options, or expose this as an additional option `:indent-with-indicator`

**Comment by lread** [comment]
Thanks for the issue @agorgl!
I vaguely remember wondering about how this all works, I guess now is the time!

So, from SnakeyYAML javadocs:
- `setIndent` Define indentation. Must be within the limits (1-10)
- `setIndicatorIndent` Set number of white spaces to use for the sequence indicator '-'
- `setIndentWithIndicator` Set to true to add the indent for sequences to the general indent

Those descriptions do not give me a clear idea of what will actually happen. 
Time to fire up the REPL!

## Default Behavior of Indentation

```Clojure
(require '[clj-yaml.core :as yaml])

(def data {1234567 [{:a 1 :b 2} {:c 3 :d 4}]})
```

Default block style output:
```clojure
(println (yaml/generate-string data :dumper-options {:flow-style :block}))
```
Produces:
```yaml
1234567:
- a: 1
  b: 2
- c: 3
  d: 4
```

Override default `indent`:
```clojure
(println (yaml/generate-string data :dumper-options {:flow-style :block :indent 5}))
```
Produces
```yaml
1234567:
-    a: 1
     b: 2
-    c: 3
     d: 4

```
Override default `indicator-indent`:
```clojure
(println (yaml/generate-string data :dumper-options {:flow-style :block :indent 5 :indicator-indent 2}))
```
Produces:
```yaml
1234567:
  -  a: 1
     b: 2
  -  c: 3
     d: 4
```

Ok so by default, the `indicator-indent` controls indentation of `-` independent of `indent`.

## What you'd like
So without `setIndicatorWithIndent`, there is no way to say please indent by 2 but for arrays, indent by 4 with an indicator indent of 2. (Which agreed, is a common convention).

Just to make sure I understand `setIndicatorWithIndent`, I've hacked in support for `:indent-with-indicator` to make sure I understand its effect.

If `:indicator-indent` is not overridden, it has no effect:

```clojure
(println (yaml/generate-string data :dumper-options {:flow-style :block
                                                     :indent-with-indicator true}))
```
Produces:
```yaml
1234567:
- a: 1
  b: 2
- c: 3
  d: 4
```
```clojure
(println (yaml/generate-string data :dumper-options {:flow-style :block :indent 5
                                                     :indent-with-indicator true}))
```
Produces:
```yaml
1234567:
-    a: 1
     b: 2
-    c: 3
     d: 4
```
But when also specifying `:indicator-indent` behavior changes:

```clojure
(println (yaml/generate-string data :dumper-options {:flow-style :block :indent 5 :indicator-indent 2
                                                     :indent-with-indicator true}))
```
```yaml
1234567:
  -    a: 1
       b: 2
  -    c: 3
       d: 4
```
We still have the indicator indented by 2 but the total indentation is now 7, not 5.

## Conclusion
I see your point!

We don't want to change the default of `indentWithIndicator` as that would change behaviour for folks who are using `:indicator-indent`. 

So we'll add `:indent-with-indicator`.

Without running examples through my REPL, I could not intuitively figure out how this works at all, so I think we should update the user guide.

Since my head is in this already, I can write up the PR (unless you were very excited by the idea of writing up a PR?).

**Comment by agorgl** [comment]
By all means go ahead, I'm eager to try it in the next release!
